version: '3.7'

services:

  springboot-app:
    build: .
    image: cristorresf/a2censo-service
    container_name: springboot-container
    ports:
      - 8080:8080
    networks:
      - springboot-mysql
    depends_on:
      - mysql-dev

  mysql-dev:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: a2censo
    ports:
      - 13306:3306
    networks:
      - springboot-mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data: {}
networks:
  springboot-mysql:


